### ISSUE TITLE
Attachments support

### ISSUE THREAD

**Issue by spajus** [spajus/gmail4j#1]
Moved from googlecode.com issue tracker: https://code.google.com/p/gmail4j/issues/detail?id=23

**Comment by Rodorush** [comment]
Hello, please, where I find the .jar file of the version 0.5 ? Because I am beginner in Java and I just know working with this file, importing it in my project. My teacher said me that there is a way to compile the code, but unfortunately I don´t know how to do it.

**Comment by spajus** [comment]
You should learn how to build it instead. It's very easy - you have to install git, clone the source code like this: 

  git clone https://github.com/spajus/gmail4j.git

Then install Maven (maven.apache.org), and run it inside gmail4j dir:

  mvn package

You will find gmail4j jar in target/ directory after its done. Also, read this: http://maven.apache.org/guides/getting-started/maven-in-five-minutes.html
