### ISSUE TITLE
master compilation

### ISSUE THREAD

**Issue by invasionofsmallcubes** [spajus/gmail4j#13]
Can you explain how to compile the master repository? When I try to do it I get

[INFO] --- maven-source-plugin:2.1.2:jar (default) @ gmail4j ---
[INFO] Building jar: /home/eianni/Bravofly/BravoflyGitRep/gmail4j/target/gmail4j-0.5-SNAPSHOT-sources.jar
[INFO] 
[INFO] --- maven-gpg-plugin:1.1:sign (sign-artifacts) @ gmail4j ---
GPG Passphrase: ***************

Do I need to configure something about GPG?

**Comment by strusewych** [comment]
I got around it by removing:

``` xml
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-gpg-plugin</artifactId>
                <version>1.1</version>
                <executions>
                    <execution>
                        <id>sign-artifacts</id>
                        <phase>verify</phase>
                        <goals>
                            <goal>sign</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
```

from my local pom.xml

**Comment by spajus** [comment]
This was used for releasing the jar to public maven repository. Haven't done this in a while, and things may have changed. I'd probably need to tighten things up a little and release a new version sometime soon.

**Comment by invasionofsmallcubes** [comment]
I just removed the plugin. I'll try to login and let you know.
Can I ask here another question or do I need to open another issue? It's a question on api usage.

**Comment by spajus** [comment]
@invasionofsmallcubes It would be better to open a new issue relevant to your questions, that way people will find it more easily when looking for similar answers.

**Comment by invasionofsmallcubes** [comment]
it's working without problem even after the plugin was removed. Thank you.
