### ISSUE TITLE
Can't support unicode character in message 

### ISSUE THREAD

**Issue by shaoliu08** [spajus/gmail4j#4]
Hi Tomas,

I was trying to use this library to retrieve message but found it didn't support unicode character in message. Can you please look into it? Gmail4j is a great library for Gmail. I love it!

Thanks!

Mercury

**Comment by PavelVinogradov** [comment]
Did you can provide simple code sample for this problem?

**Comment by shaoliu08** [comment]
Here is the code. Thanks!
            final ImapGmailClient client = new ImapGmailClient();
            final ImapGmailConnection connection = new ImapGmailConnection();

```
        try {
            connection.setLoginCredentials(c);

            client.setConnection(connection);
            int i = 0;
            final List<GmailMessage> unreadMessages = client.getPriorityMessages(false);
            for (GmailMessage message : unreadMessages) {
                String text = message.getContentText();
                System.out.println(message.getFrom());
                if (i++ > 10) break;
            }

        } catch (final Exception e) {
        } finally {
            client.disconnect();
        }
```

**Comment by PavelVinogradov** [comment]
I'm write sample code to display unread message and write email with unicode in from, subject and content fields.
All works fine:

> 1429 [JavaMail-EventQueue] DEBUG com.googlecode.gmail4j.javamail.ImapConnectionHandler  - ImapGmailConnection ConnectionInfo:{user:gm4jtest;host:imap.gmail.com;port:993} is opened.
> From: BoardGamGeek Secret Santa ąžuolėlį <....>
> Subject: ąžuolėlį
> Content: ąžuolėlį
> 
> <div dir="ltr">ąžuolėlį</div>

Did you can forward problem message to gm4jtest gmail address.

**Comment by shaoliu08** [comment]
I can get the correct character now after I change the file encoding from MacRoman to UTF-8. 
Thanks a lot!
