### ISSUE TITLE
Getting the source from a message

### ISSUE THREAD

**Issue by cambiph** [spajus/gmail4j#7]
Hello,

Is it in any way possible to get the source from an unread email?
I got a URL in the mail and when I print the content it just says "link".
I need to get the href from the link.

Thanks in advance.
Cheers

**Comment by spajus** [comment]
You have to use [ImapGmailClient](https://github.com/spajus/gmail4j/blob/master/src/main/java/com/googlecode/gmail4j/javamail/ImapGmailClient.java) to be able to get email body.

**Comment by cambiph** [comment]
I see, but it seems our corporate firewall is blocking port 993 and 143.
